server.port=8080
stats.server.url=http://stats-server:9090

management.endpoints.web.exposure.include=health

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://main-db:5432/ewm_main
spring.datasource.username=ewm_user
spring.datasource.password=ewm_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.web.page-serialization-mode=VIA_DTO

spring.jpa.hibernate.ddl-auto=update

logging.level.ru.practicum.statsrvc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC