server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/stats
spring.datasource.username=stats_user
spring.datasource.password=stats_password

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.ru.practicum.stats=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jackson.serialization.write-dates-as-timestamps=false